import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import copy from "esbuild-plugin-copy";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"onnxruntime-node",
		"sharp",
		...builtins,
	],
	format: "cjs",
	target: "node18",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	outfile: "main.js",
	minify: prod,
	plugins: [
		copy({
			assets: [
				{
					from: "./manifest.json",
					to: "./.vault/.obsidian/plugins/kreativ/manifest.json",
				},
				{
					from: "./main.js",
					to: "./.vault/.obsidian/plugins/kreativ/main.js",
				},
				{
					from: "./styles.css",
					to: "./.vault/.obsidian/plugins/kreativ/styles.css",
				},
			],
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
