import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import copy from "esbuild-plugin-copy";
import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const devVaultPath = ".vault/.obsidian/plugins/kreativ";

// Ensure devVaultPath exists
if (!fs.existsSync(devVaultPath)) {
	fs.mkdirSync(devVaultPath, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	platform: "browser",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	metafile: true,
	minify: prod,
	plugins: [
		copy({
			assets: [
				{
					from: "./manifest.json",
					to: path.join(devVaultPath, "manifest.json"),
				},
				{
					from: "./main.js",
					to: path.join(devVaultPath, "main.js"),
				},
				{
					from: "./styles.css",
					to: path.join(devVaultPath, "styles.css"),
				},
			],
		}),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
