import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import copy from "esbuild-plugin-copy";
import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const devVaultPath = ".vault/.obsidian/plugins/kreativ";
const distPath = "dist";

// Ensure target paths exist
if (prod) {
	// Clean and create dist folder for production
	if (fs.existsSync(distPath)) {
		fs.rmSync(distPath, { recursive: true });
	}
	fs.mkdirSync(distPath, { recursive: true });
} else {
	// Create dev vault path for development
	if (!fs.existsSync(devVaultPath)) {
		fs.mkdirSync(devVaultPath, { recursive: true });
	}
}

/**
 * Custom plugin to bundle worker files and inline them as strings.
 * Files matching *.worker.ts are bundled separately (with all dependencies)
 * and imported as a JavaScript code string.
 */
const inlineWorkerPlugin = {
	name: "inline-worker",
	setup(build) {
		build.onResolve({ filter: /\.worker\.ts$/ }, (args) => {
			return {
				path: path.resolve(args.resolveDir, args.path),
				namespace: "inline-worker",
			};
		});

		build.onLoad(
			{ filter: /.*/, namespace: "inline-worker" },
			async (args) => {
				// Bundle the worker file with all its dependencies
				const result = await esbuild.build({
					entryPoints: [args.path],
					bundle: true,
					write: false,
					format: "iife",
					platform: "browser",
					target: "es2018",
					minify: prod,
				});

				const workerCode = result.outputFiles[0].text;

				// Return the bundled code as a string export
				return {
					contents: `export default ${JSON.stringify(workerCode)};`,
					loader: "js",
				};
			}
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	platform: "browser",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: prod ? path.join(distPath, "main.js") : "main.js",
	metafile: true,
	minify: prod,
	plugins: [
		inlineWorkerPlugin,
		// Copy artifacts to appropriate location based on mode
		...(prod
			? [
					// Production: copy manifest and styles to dist/ (same dir as main.js)
					copy({
						assets: [
							{
								from: "./manifest.json",
								to: "./manifest.json",
							},
							{
								from: "./styles.css",
								to: "./styles.css",
							},
						],
					}),
			  ]
			: [
					// Dev: copy all artifacts to dev vault
					copy({
						assets: [
							{
								from: "./manifest.json",
								to: path.join(devVaultPath, "manifest.json"),
							},
							{
								from: "./main.js",
								to: path.join(devVaultPath, "main.js"),
							},
							{
								from: "./styles.css",
								to: path.join(devVaultPath, "styles.css"),
							},
						],
					}),
			  ]),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
